services:
  php-apache:
    build: .
    container_name: dreamjournal_app
    ports:
      - "8082:80"
    volumes:
      - ./backend:/var/www/html/backend
      - ./presentation/frontend:/var/www/html/frontend
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=dreamjournal
      - DB_USER=root
      - DB_PASS=root
    networks:
      - dreamjournal_network

  mysql:
    image: mysql:8.0
    container_name: dreamjournal_db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreamjournal
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/repository/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dreamjournal_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dreamjournal_phpmyadmin
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - dreamjournal_network

volumes:
  mysql_data:

networks:
  dreamjournal_network:
    driver: bridge

